name = "QuantumESPRESSOExtensions"
uuid = "118282d6-3134-473f-a7d0-9c52f5e2a9d2"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbInitioSoftware = "bd21691c-901c-41c3-939b-9c02ec4395ba"
CrystallographyBase = "93b1d1cd-a8ea-4aa5-adb1-b2407ea0ba8d"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
QuantumESPRESSOBase = "51b62caa-b28f-11e9-38c2-1f67cb498e05"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
Mustache = "1"
QuantumESPRESSOBase = "0.10"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
